Repository home-assistant/companion.home-assistant, pull requests merged in 2020-11, with the labels that each got.

#379 Update index.md
  docs/getting_started/index.md
Labels: cla-signed

#380 Correct table for android sensors
  docs/core/sensors.md
Labels: cla-signed

#381 Mention usage of alarm_stream_max for TTS notifications
  docs/notifications/basic.md
  docs/notifications/critical.md
Labels: cla-signed

#367 Add media browser example
  docs/notifications/attachments.md
Labels: cla-signed, hacktoberfest-accepted

#383 Add info about keyguard sensors
  docs/core/index.md
  docs/core/sensors.md
Labels: cla-signed

#382 Remove beta flags for next android release
  docs/core/sensors.md
  docs/integrations/android-power-menu.md
  docs/integrations/android-widgets.md
  docs/integrations/app-events.md
  docs/notifications/actionable.md
  docs/notifications/basic.md
  docs/notifications/cleared.md
  docs/notifications/commands.md
  docs/notifications/critical.md
Labels: cla-signed

#384 Remove sleep as android sensors
  docs/core/index.md
  docs/core/sensors.md
Labels: cla-signed

#385 Remove keyguard beta label
  docs/core/sensors.md
Labels: cla-signed

#388 Mention including location with sensor updates
  docs/core/location.md
Labels: cla-signed

#389 Add info about controlling the volume level on android
  docs/notifications/commands.md
Labels: cla-signed

#386 Added documentation for chronometer notifications
  docs/notifications/basic.md
Labels: cla-signed, has-parent

#390 Add info about the current version sensor
  docs/core/index.md
  docs/core/sensors.md
Labels: cla-signed

#391 Add some more troubleshooting steps for android
  docs/notifications/basic.md
  docs/troubleshooting/setup.md
Labels: cla-signed

#393 Enhance chronometer notification documentation
  docs/notifications/basic.md
Labels: cla-signed

#392 Add info about the current time zone sensor
  docs/core/index.md
  docs/core/sensors.md
Labels: awaits-parent, cla-signed, has-parent

#394 Remove beta labels for android release 3.0.2
  docs/core/sensors.md
  docs/notifications/basic.md
  docs/notifications/commands.md
Labels: cla-signed

#375 Update siri-shortcuts.md
  docs/integrations/siri-shortcuts.md
Labels: cla-signed, hacktoberfest-accepted

#396 Make some additional troubleshooting adjustments
  docs/notifications/basic.md
  docs/troubleshooting/setup.md
Labels: cla-signed

#397 Add info about app data and memory sensors
  docs/core/index.md
  docs/core/sensors.md
Labels: awaits-parent, cla-signed

#401 Add info about app usage sensors for android
  docs/core/index.md
  docs/core/sensors.md
Labels: cla-signed

#402 Fix typo on line 222 in sensors.md
  docs/core/sensors.md
Labels: cla-signed

#400 Add another example for TTS notifications
  docs/notifications/basic.md
Labels: cla-signed

#405 Added F-Droid download link
  docs/core/android-flavors.md
Labels: cla-signed
